### ISSUE TITLE
jwt:generate broken!

### ISSUE THREAD

**Issue by paparyku** [tymondesigns/jwt-auth#1425] opened 2017-12-20 22:11 UTC
**php artisan jwt:generate** - is broken!
```

php artisan jwt:generate

In BoundMethod.php line 135:

  Method Tymon\JWTAuth\Commands\JWTGenerateCommand::handle() does not exist
```

**Comment by helpceo** [comment] 2017-12-21 10:26
me too

**Comment by rdarcy1** [comment] 2017-12-22 11:21
This is because the command class adheres to the Laravel 4 command interface, which uses a `fire()` method instead of `handle()`. As a quick and dirty fix you can add the following to `Tymon\JWTAuth\Commands\JWTGenerateCommand`:

```php
// JWTGenerateCommand.php

public function handle()
{
    $this->fire();
}
```

Alternatively, the issue is fixed in the development version so you could pull in that version and use the [new docs](https://jwt-auth.readthedocs.io/en/docs/laravel-installation/). No idea how stable the dev version is at the moment.

**Comment by 1e4** [comment] 2018-01-08 19:27
Since we are doing dirty hacks you can also just change the method `fire()` to `handle()` within `\vendor\tymon\jwt-auth\src\Commands\JWTGenerateCommand.php`

**Comment by tymondesigns** [comment] 2018-01-19 16:44
Yes I'm aware of this.. version `0.5.*` doesn't have full support for Laravel 5.5. You would need to use the newer release

**Closed as completed by tymondesigns** 2018-01-19 16:44 UTC
