### ISSUE TITLE
Method [viaRemember] does not exist.

### ISSUE THREAD

**Issue by tom2drum** [tymondesigns/jwt-auth#1436] opened 2017-12-30 04:26 UTC
I'm trying to get current user using Auth::guard()->user() method and providing token via header, but i'm getting error: "BadMethodCallException  Method [viaRemember] does not exist." Does anybody have any ideas why?

**Comment by jamesh38** [comment] 2018-01-23 20:36
I'm having the same issue @tom-aglow have you had any luck resolving? @tymondesigns Have you heard of this?

**Comment by tom2drum** [comment] 2018-01-24 03:38
@jamesh38 unfortunately, no :( i'll let you know if i can solve the problem somehow.

**Comment by tymondesigns** [comment] 2018-01-24 12:41
The `viaRemember` method only exists on the session guard, not the jwt one. what does your `config/auth.php` look like?

**Comment by tom2drum** [comment] 2018-01-24 17:16
[config/auth.php](https://github.com/tom-aglow/board_buddies/blob/master/config/auth.php) - this is mine. should i use api driver as default then? /feel stupid/

**Comment by jamesh38** [comment] 2018-01-24 17:26
[Here is mine](https://hastebin.com/eyayudezop.xml). I have multi auth on mine but I'm simply using the eloquent driver on a different Model. My items are globally name spaced btw.

**Comment by tymondesigns** [comment] 2018-01-24 17:57
@tom-aglow Yes you should specify the `api` guard or set it to be the default `Auth::guard('api')->user()`

@jamesh38 should work just fine if you use the `api` guard

**Closed as completed by tymondesigns** 2018-01-24 17:57 UTC

**Comment by jamesh38** [comment] 2018-01-24 18:08
Yah that's where I'm stumped I'm getting this error when going through any route that is protected by the JWT (api) guard.

![error](https://i.gyazo.com/b6a22c4df1916a856cd6f23fc0342bcb.png)

```
Route::group(['middleware' => 'api', 'prefix' => 'api/auth'], function ($router) {
	Route::post('login', 'TokenController@login');
	Route::post('logout', 'TokenController@logout');
	Route::post('refresh', 'TokenController@refresh');
	Route::get('me', 'TokenController@me');
	Route::post('register', 'AppUserController@register');
});
```
There are my routes with the token controller having this in the constructor.

```
public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['login']]);
    }

```

Any ideas?

Thank you by the way for the help.

**Comment by tymondesigns** [comment] 2018-01-24 18:21
Hmm well it looks like the error is being caused by the AuthenticateSession middleware here https://github.com/laravel/framework/blob/5.5/src/Illuminate/Session/Middleware/AuthenticateSession.php#L42

in your `app/Http/Kernel.php` file.. what middleware is being loaded where? specifically `\Illuminate\Session\Middleware\AuthenticateSession::class,`

**Comment by tom2drum** [comment] 2018-01-24 18:23
thanks @tymondesigns. so sorry for stupid question 😊

**Comment by jamesh38** [comment] 2018-01-24 20:49
[Here is my Http Kernel](https://hastebin.com/guficajaye.tex)

Thanks for the help here. I realize this isn't your code at this point. Ha.

**Comment by tymondesigns** [comment] 2018-01-24 22:43
No worries, have you tried commenting out `\Illuminate\Session\Middleware\AuthenticateSession::class,` ?

**Comment by jamesh38** [comment] 2018-01-25 00:34
I have. Same result. Completely out of the application or just out of the
web stack of middleware?

**Comment by jamesh38** [comment] 2018-01-29 18:29
Well it looks like commenting that out did the trick. I do have a custom provider I am adding to the app that has to be what is cuasing the issue.

**Comment by wisammechano** [comment] 2018-07-11 18:33
I face this problem when I request a web route with Authorization Token in the header, and the default guard is api driven by jwt.

The problem seems to be that when Auth token is valid the guard resolve the user and it is authenticated then the AuthenticateSession middleware try to authenticate session presuming SessionGuard while you have JWTGuard.

**Comment by Frozire** [comment] 2019-03-22 08:32
> I face this problem when I request a web route with Authorization Token in the header, and the default guard is api driven by jwt.
> 
> The problem seems to be that when Auth token is valid the guard resolve the user and it is authenticated then the AuthenticateSession middleware try to authenticate session presuming SessionGuard while you have JWTGuard.

I am running into the same issue, did you find any workarounds? Or did you disable the AuthenticatesSession middleware too?

**Comment by aligajani** [comment] 2020-03-10 17:11
I fixed this using the following custom middleware:

```<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Contracts\Auth\Factory as AuthFactory;

class CustomAuthenticateSessionMiddleware
{
    /**
     * The authentication factory implementation.
     *
     * @var \Illuminate\Contracts\Auth\Factory
     */
    protected $auth;

    /**
     * Create a new middleware instance.
     *
     * @param  \Illuminate\Contracts\Auth\Factory  $auth
     * @return void
     */
    public function __construct(AuthFactory $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // if vapor/signed-storage/url , just ignore this middleware entirely
       if ($request->has("ignore_web_middleware") || $request->ignore_web_middleware ) {
           return $next($request);
       }
        if (! $request->hasSession() || ! $request->user()) {
            return $next($request);
        }

        if ($this->auth->viaRemember()) {
            $passwordHash = explode('|', $request->cookies->get($this->auth->getRecallerName()))[2];

            if ($passwordHash != $request->user()->getAuthPassword()) {
                $this->logout($request);
            }
        }

        if (! $request->session()->has('password_hash')) {
            $this->storePasswordHashInSession($request);
        }

        if ($request->session()->get('password_hash') !== $request->user()->getAuthPassword()) {
            $this->logout($request);
        }

        return tap($next($request), function () use ($request) {
            $this->storePasswordHashInSession($request);
        });
    }

    /**
     * Store the user's current password hash in the session.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function storePasswordHashInSession($request)
    {
        if (! $request->user()) {
            return;
        }

        $request->session()->put([
            'password_hash' => $request->user()->getAuthPassword(),
        ]);
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    protected function logout($request)
    {
        $this->auth->logoutCurrentDevice();

        $request->session()->flush();

        throw new AuthenticationException;
    }
}

```

**Comment by Synchro** [comment] 2023-05-09 08:21
I ran into this and found a simple fix. Most of my tests are for my API routes, but these ones were web routes. I was setting up an auth session using `Passport::actingAs()` (and getting this error), which I simply changed to `$this->actingAs()`, and that seems to appease the web route auth gods.
