### ISSUE TITLE
Not Creating Valid Tokens

### ISSUE THREAD

**Issue by codeorganic** [tymondesigns/jwt-auth#124] opened 2015-05-26 21:35 UTC
I have tried a few times now in order to create a signed token, verified with jwt.io.

The issue is that my tokens are created with a valid signature, but even if I type in my signing key they tokens still appear to be unsigned.

**Comment by tymondesigns** [comment] 2015-05-26 23:18
This seems to be related to https://github.com/namshi/jose/issues/35

I will be sure update the dependencies on the next release, since it has been released in`5.0.0`

**Closed by tymondesigns** 2015-05-26 23:18 UTC

**Comment by tymondesigns** [comment] 2015-05-26 23:37
I just confirmed this is indeed the issue.. having tested it using the develop branch

**Comment by codeorganic** [comment] 2015-05-27 18:19
Could this also be part of the unit tests on our end?

Also when will the next release be for us?

**Comment by tymondesigns** [comment] 2015-05-27 20:10
Not sure what you mean regarding your unit tests?

I am aiming to release within the next week or 2
