### ISSUE TITLE
Should status code be 400 or 401 if token is not provided

### ISSUE THREAD

**Issue by mehrdaad** [tymondesigns/jwt-auth#1024] opened 2017-02-28 16:21 UTC
The title is self explanatory, If ``Authorization`` header is absent what would be appropriate status code?  
I see if u use ``api.auth`` middleware from Dingo it will be 401 while jwt will be 400.

**Comment by andrewmclagan** [comment] 2017-03-07 05:01
Agreed, i was about to raise the same issue before I found this.

- `400` denotes a mal-formed HTTP request.
- `401` denotes the the request was unauthorised 

Logic would dictate a request failing to provide a token is `401` not authorised rather then `400` badly formed. 

Clients accessing a RESTful resource expect response codes to explain correctly what has happened. In this case authentication failure. The client can thus handle a typical `401`.

Now clients are typically a frontend website, mobile app or other services. Responding to the root cause which is "missing auth" is simpler "Hey i got 401 back, there fore i will display the unauthorized dialog" rather then "Hey I got 400 back, i will display the 'something went wrong' dialog".

The offical specs says `401` is 

> specifically for use when authentication is required ... or has not yet been provided.

## Official REST specs

**400 Bad Request**
The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, too large size, invalid request message framing, or deceptive request routing) [...]

**401 Unauthorized**
Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided. [...]

**Comment by mehrdaad** [comment] 2017-03-07 20:04
@andrewmclagan thanks, but this seems like a bug rather than a decision.  
Issuing ``400`` status code for not providing token wrong at least for me.  
Do you agree with me too?

**Comment by andrewmclagan** [comment] 2017-03-08 00:33
Sure i could do this.

**Comment by mehrdaad** [comment] 2017-03-09 20:40
@andrewmclagan appreciated.

**Comment by andrewmclagan** [comment] 2017-03-10 01:56
@mehrdaad Just finding time to fix the issues with the PR now

**Comment by tymondesigns** [comment] 2017-03-25 22:29
merged :)

**Closed by tymondesigns** 2017-03-25 22:29 UTC

**Comment by manuel-84** [comment] 2019-10-29 10:10
I'm having this issue again with latest v

**Comment by dennisvang** [comment] 2025-01-29 15:17
>Official REST specs

(from [comment above])

@andrewmclagan Could you provide a link to these "official" REST specs? 

I only know https://ics.uci.edu/~fielding/pubs/dissertation/top.htm

[comment above]: https://github.com/tymondesigns/jwt-auth/issues/1024#issuecomment-284622542
