### ISSUE TITLE
jwt-auth creates claims i have not included in my token.

### ISSUE THREAD

**Issue by alvassin** [tymondesigns/jwt-auth#348] opened 2015-12-14 11:02 UTC
I config i specified some claims i would like to see.

Then, using http://jwt.io/ i have created jwt token with only fields `uid` (my custom claim) and `exp` and tried to see, why it is processed as valid.

I found that there are a lot of optional claims (iss, iat, nbf, jti) created automatically (which i did not have in token). Why?! It would be very likely to have ability to disable this behaviour.

P.S. there must be array_diff, currently it does not check anything:
https://github.com/tymondesigns/jwt-auth/blob/master/src/Validators/PayloadValidator.php#L48

**Comment by kylestev** [comment] 2015-12-16 05:50
You have a good point. That validator is accepted in the `Factory` class however [it is not referenced outside the constructor](https://github.com/tymondesigns/jwt-auth/blob/8298edc879ef5f97ccb3d805260d7c2e1123fbcf/src/Factory.php#L41) and is a protected member. I think that's the root cause.

**Comment by tdhsmith** [comment] 2016-01-06 23:23
The `array_diff` change has [already been fixed on develop](https://github.com/tymondesigns/jwt-auth/commit/4fc23d2b8632546255956ff1ad2723851f0967f5).

The extra claims are necessary to establish timelines and unique identifiers for the tokens. It is true that they are not _technically_ required by the JWT standard, but in this package they are used to handle expiration and validation. You will find this is true of nearly all JWT authentication systems, because knowing when a token was issued and who it was issued by are usually important details.

**Comment by alvassin** [comment] 2016-02-07 13:19
@tdhsmith Them problem is you don't care about integration with legacy / non-laravel systems.

It is ok to validate such claims - but if it is required. I can't get why it is not possible to configure claims i want to see present & to be validated, it is obvious issue.

It is very confusing, that you get fatally different object, with invalid (yeah, why do you set issued time for example?) data. You are invalidating token itself, because it does not have some properties.

I understand approach to provide as less interface to users as possible. But it's a library, module built for developers.

**Comment by alvassin** [comment] 2016-02-07 14:28
@tdhsmith thanks for fix information. When it will be available via composer?

**Comment by tdhsmith** [comment] 2016-02-08 17:58
> Them problem is you don't care about integration with legacy / non-laravel systems.

> It is ok to validate such claims - but if it is required by application. I can't get why it is not possible to configure claims i want to see present & to be validated, it is obvious issue.

I agree with you that the current settings aren't enough to support those situations. How much should this library cover, though? I'm not sure. People with advanced/legacy needs are still able to use the underlying Namshi library (or any of the other JWT encoding/decoding libraries for PHP).

I would love to see something more elegant & configurable for how claim validations and defaults are handled, but perhaps not if it comes at the cost of confusing or encumbering the main user base.

> When it will be available via composer?

I'm not the maintainer, so I'm not certain. You _can_ use `0.6.*@dev` to pull the current develop branch, but that's a moving target, so a bad idea for production.

**Comment by tymondesigns** [comment] 2016-02-19 23:34
@alvassin This is already possible using the `setDefaultClaims()` setter on the `Factory` instance. e.g.

```php
// In a service provider
app('tymon.jwt.payload.factory')->setDefaultClaims(['uid', 'exp']);
```

**Closed by tymondesigns** 2016-02-19 23:34 UTC

**Comment by jmdavid** [comment] 2017-11-21 19:10
It doesn't work:
`$factory = JWTAuth::factory()->setDefaultClaims(['iat', 'exp']);
        $payload = $factory->aud(...`

I still have nbf and jti.
