### ISSUE TITLE
Laravel 5.5. jwt:generate issue

### ISSUE THREAD

**Issue by Milos0110** [tymondesigns/jwt-auth#1298] opened 2017-09-03 10:28 UTC
Hi all, 
I came upon one issue when I try to run `php artisan jwt:generate` I get the Reflection Exception saying "[ReflectionException]  Method Tymon\JWTAuth\Commands\JWTGenerateCommand::handle() does not exist"

Both Facades and service providers are entered properly and they are valid.

Also for people who have a struggle to make it work I can advise one solution. Go to **JWTGenerateCommand.php** file located in **vendor/tymon/src/Commands** and paste this part of code ` public function handle() {
        $this->fire();    
    }`

I know this is not an elegant solution, but it works. I hope this might help until official fix arrive.

Have a nice day.

**Comment by hughsaffar** [comment] 2017-09-04 13:44
I guess this is already resolved by #1255.

**Comment by ghost** [comment] 2017-09-05 01:13
Acho que não foi.

**Comment by Chintan7027** [comment] 2017-09-08 20:08
Any solution for this ? I am facing same problem

**Comment by fengerwoo** [comment] 2017-09-11 09:29
非常感谢

**Comment by packytagliaferro** [comment] 2017-09-14 19:05
I just added this package to my Laravel 5.5 project 

Composer:
`"tymon/jwt-auth": "0.5.*"`

added the following to the app config:

Providers
`Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,`

Aliases
```
'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
 'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class,
```

then: `php artisan jwt:generate`

Error: 

```
[ReflectionException]
  Method Tymon\JWTAuth\Commands\JWTGenerateCommand::handle() does not exist
```

**Comment by hughsaffar** [comment] 2017-09-14 21:03
The PR for this issue has been merged into `develop` branch.
Try `composer require tymon/jwt-auth:dev-develop --prefer-source`
For Service Provider, you need to check `docs` branch.

**Comment by estenger** [comment] 2017-09-15 04:12
@Milos0110 `public function handle() { $this->fire(); }` worked for me. Thanks!

**Comment by tijanmdr** [comment] 2017-09-15 07:41
I don't think messing with library is a good idea. Rather try
 
`composer require tymon/jwt-auth:dev-develop --prefer-source` 

Delete `jwt.php` (if previous version is installed) file from config folder and then try `php artisan vendor:publish`. It'll list all the possible configurations to publish. You'll need to choose JWT.

and update provider in `config/app.php` as
- If line `Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class` exists, update to `Tymon\JWTAuth\Providers\LaravelServiceProvider::class`
- Else, add `Tymon\JWTAuth\Providers\LaravelServiceProvider::class`

Then implement `User` model with `JWTSubject` and implement following functions: 

```
public function getJWTIdentifier()
{
    return $this->getKey();
}
public function getJWTCustomClaims()
{
    return [];
}
```

**Comment by Onyekam** [comment] 2017-09-17 15:53
Neither adding `public function handle() { $this->fire(); }` nor doing `composer require tymon/jwt-auth:dev-develop --prefer-source` worked for me. I'm on build 423

**Comment by lomholdt** [comment] 2017-09-17 19:29
Using `dev-develop` version worked for me on Laravel 5.5.4. The command for generating the key has changed from `jwt:generate` to `jwt:secret`.

**Comment by Punksolid** [comment] 2017-09-19 07:33
I did what @tijanmdr says and then jwt:secret and  worked.

**Comment by tijanmdr** [comment] 2017-09-19 07:47
@Onyekam after `composer require tymon/jwt-auth:dev-develop --prefer-source`, delete `jwt.php` file from `config` folder and then try `php artisan vendor:publish`. It'll list all the possible configurations to publish. You'll need to choose JWT. 

Then follow the steps above. :)

**Comment by SwapnilEI** [comment] 2017-09-20 08:16
public function handle() { $this->fire(); } this worked for me. Thanks @Milos0110  👍

**Comment by jaksm** [comment] 2017-09-20 14:38
Why shouldnt you just rename fire() to handle()? I did this and all works fine.

**Comment by SwapnilEI** [comment] 2017-09-20 14:43
@jaksa-m yup correct. I have renamed fire to handle now.

**Comment by jaksm** [comment] 2017-09-20 14:54
I'm glad it helped!

**Comment by pkitatta** [comment] 2017-09-27 09:58
`fire()` to `handle()` works just fine. Thanks @jaksa-m

**Comment by usamamuneerchaudhary** [comment] 2017-10-05 22:26
handle() { $this->fire() } worked for me.

**Comment by flxxyz** [comment] 2017-10-11 14:28
good job @Milos0110

**Comment by ojasseh** [comment] 2017-10-14 12:54
woow..Thanks @tijanmdr this works for me...

**Comment by lxiaoxiang** [comment] 2017-11-10 08:01
@Milos0110 Thanks

**Comment by bencun** [comment] 2017-11-13 12:22
Do what @tijanmdr suggested, just remember to remove the service provider and all aliases from app.php before trying to pull the latest version with composer. It works 100%.

**Comment by tijanmdr** [comment] 2017-11-20 07:29
Do anyone have the solution for this. The JWT has overridden default `Auth`. While doing 
```
use Illuminate\Support\Facades\Auth;

.....
.....
.....

$user = Auth::attempt([
    'email' => $request['email'],
    'password' => $request['password'],
]);
```
This gives me `Bearer token`

**Comment by tijanmdr** [comment] 2017-11-20 07:47
Do anyone have the solution for this.JWT has overridden default `Auth` functionality. While doing 
```
use Illuminate\Support\Facades\Auth;

.....
.....
.....

$user = Auth::attempt([
    'email' => $request['email'],
    'password' => $request['password'],
]);
```
This gives me `Bearer token`

**Comment by genyded** [comment] 2018-01-25 01:19
Is anyone going to update the docs to reflect this??

**Comment by rezasys2** [comment] 2018-02-04 07:36
thanks @Milos0110.
Why they didnt add this function? and require it!!

**Comment by opannapo** [comment] 2018-02-05 17:58
@Milos0110 excelent 💯 . Create the handle() function then execute fire()

**Comment by rezamax** [comment] 2018-02-10 08:53
thanks @Milos0110

**Comment by rojonunoo** [comment] 2018-02-22 13:51
handle() { $this->fire() } worked for me. Did the Trick! Thanks buddy God bless you @Milos0110

**Comment by rzlyp** [comment] 2018-03-02 03:29
thanks you.

**Comment by li3007liuu** [comment] 2018-04-09 10:46
jwt:generate 调用的命令函数handle（）在新版已经没有了，在新版中的函数是fire()；所以修改 vendor/tymon/jwt-auth/src/Commands/JWTGenerateCommand.php文件，类中间添加语句public function handle()
    {
        $this->fire();
    } 再次运行则解决上述问题。

**Comment by vesper8** [comment] 2018-04-10 12:22
I wrote this little command to rename all the fire() to handle(). After running it then the command works fine.

```
find ./vendor -type f \( -name '*Command.php' \) -exec grep -q 'fire()' {} \; ! -exec grep -q 'handle()' {} \; -print0 | xargs -0 sed -i 's@function fire(@function handle(@g'
```

**Comment by connor11528** [comment] 2018-04-11 20:52
Github doesn't support PRs to the wiki. Can we update the changes to support Laravel 5.5 and 5.6? 

Thank you!

**Comment by ImArtur** [comment] 2018-04-12 12:17
Don't mess with external lib. Just use dev version as @lomholdt mention.

**Comment by connor11528** [comment] 2018-04-12 16:37
The documentation is pretty clear. Head to [the website](http://jwt-auth.readthedocs.io/en/develop/) for recent versions of Laravel. Also, use release candidate number 2 for Laravel 5.6.

There is also a nice tutorial for using this package here: https://blog.pusher.com/build-rest-api-laravel-api-resources/

**Comment by beaplat-61f** [comment] 2018-06-22 13:49
Thanks, you solved my problem

**Comment by deivamagalhaes** [comment] 2018-07-06 18:09
It's frustrating to be starting another Laravel project and this still is on dev branch... 😭

**Comment by huanghantao** [comment] 2018-07-17 07:12
thx

**Comment by islam-moneer** [comment] 2018-07-26 15:56
As I don't like messing around in package source code and pull from develop branch confused me with so many different functions so I decided to create **handle** function to fire when you run `php artisan jwt:generate` command
Run `php artisan make:command NAME` and name it as you want - you can find it in **App/Console/Commands** then open it and in 'handle()' function paste this part of code `$this->fire();` 
 Replace extended class Command with this class `use Tymon\JWTAuth\Commands\JWTGenerateCommand as Command;` and viola

**Comment by aziev** [comment] 2018-08-30 14:02
@islam-moneer when I did so I got error `The "show" option does not exist.`

**Comment by Dadan93** [comment] 2018-09-05 04:49
@Milos0110 thanks , this is worked for me

**Comment by oldskool73** [comment] 2018-09-24 02:22
@aziev fix for "The "show" option does not exist." , in your new command file...

```
/**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'jwt:secret {--show}';
```

**Comment by davidrtpereira** [comment] 2018-10-06 02:18
To work around this problem, create a class that is a default class:
Run command: php artisan make:command JWTGenerateCommand

Find to class JWTGenerateCommand (app/Console/Commands/JWTGenerateCommand):

```<?php

namespace App\Console\Commands;

use \Tymon\JWTAuth\Commands\JWTGenerateCommand as Command;

/**
 * Class Wrapper para sobrescrever o erro gerado no momento de executar o comando jwt:generate
 * @link https://github.com/tymondesigns/jwt-auth/issues/1298
 *
 * Class JWTGenerateCommand
 * @author David Pereira
 * @package App\Console\Commands
 */
class JWTGenerateCommand extends Command
{
    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Metodo chamado pelo framework no momento da execucao do comando
     */
    public function handle()
    {
        $this->fire();
    }
}`

``

After, update this file: app/Console/Kernel.php
Find to attribute $commands:

`protected $commands = [
        \App\Console\Commands\JWTGenerateCommand::class,
    ];`

Save and execute command: php artisan key:generate
output: jwt-auth secret [1ih9dGbLsfCbvhWtaUYpmtH4gEQjE4wU] set successfully.

**Comment by renepardon** [comment] 2018-11-22 12:51
Same error on latest laravel. Working solution is 

    composer require tymon/jwt-auth:dev-develop --prefer-source

Which also includes auto discovery etc. Maybe one could create a new version because using dev-develop ist not a good way to install packages.

**Comment by claytongf** [comment] 2018-12-02 23:39
Go to JWTGenerateCommand.php and replace
`public function fire()`
to
`public function handle()`

It worked well for me.

**Comment by reisdev** [comment] 2018-12-24 22:35
It still a problem. We shouldn't need to change the `JWTGenerateCommand.php` to get it working. Renaming the `fire()` method to `handle()` works fine, but it shouldn't be needed.

**Comment by hudsontavares** [comment] 2019-01-16 13:27
For the guys coming with newer versions of Laravel (I guess 5.5+), the issue is that by simply running

`composer require tymon/jwt-auth`

You'll obtain the 0.5-based version, that is not immediately compatible, interface-wise, with the latest versions of Laravel (that's why so many people says that renaming `fire` by `handle` did the job).

In order to fix that (assuming you already have installed the jwt library)

1. Change the entry on your composer.json to `"tymon/jwt-auth": "^1.0"`
2. Run `composer update`
3. Run `php artisan vendor:publish` and provide the number for the JWT package (in my clean Laravel 5.7 install, it was the 8th option)
4. Then you can run `php artisan jwt:secret` as well

A bit more sweaty than modifying the library source, but avoids this bad practice (modify 3rd party code).

**Comment by b0janix** [comment] 2019-01-28 23:30
> For the guys coming with newer versions of Laravel (I guess 5.5+), the issue is that by simply running
> 
> `composer require tymon/jwt-auth`
> 
> You'll obtain the 0.5-based version, that is not immediately compatible, interface-wise, with the latest versions of Laravel (that's why so many people says that renaming `fire` by `handle` did the job).
> 
> In order to fix that (assuming you already have installed the jwt library)
> 
> 1. Change the entry on your composer.json to `"tymon/jwt-auth": "^1.0"`
> 2. Run `composer update`
> 3. Run `php artisan vendor:publish` and provide the number for the JWT package (in my clean Laravel 5.7 install, it was the 8th option)
> 4. Then you can run `php artisan jwt:secret` as well
> 
> A bit more sweaty than modifying the library source, but avoids this bad practice (modify 3rd party code).

This works, thank you. The problem is the version of the package that you get with "composer require tymon/jwt-auth"

**Comment by ajmakoni** [comment] 2019-02-12 09:48
Summary of working solution:
1)  composer require "tymon/jwt-auth": "^1.0"
2)  composer update
3)  php artisan vendor:publish (selection Tymon\JWTAuth\Providers\LaravelServiceProvider)
4)  php artisan jwt:secret

Advantage of this solution is you **don't have to manualy add classes to config/app.php file**

**Comment by marataziat** [comment] 2019-02-13 05:38
```- The requested package tymon/jwt-auth ^1. 1.0 exists as tymon/jwt-auth[0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.10, 0.3.11, 0.3.12, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.10, 0.5.11, 0.5.12, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 1.0.0-alpha.2, 1.0.0-alpha.3, 1.0.0-alpha1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 2.0.x-dev, dev-analysis-XWvAMG, dev-develop, 1.0.x-dev, dev-master] but these are rejected by your constraint.```
Wtf dudes?

**Comment by tymondesigns** [comment] 2019-03-14 20:45
I think it's clear now that the newer version of the package is the way to go :)

**Closed as completed by tymondesigns** 2019-03-14 20:45 UTC

**Comment by vedmant** [comment] 2019-05-20 16:07
So it's still not working? For version 1.0 it says: "Your requirements could not be resolved to an installable set of packages." means it's still under development?

**Comment by vesper8** [comment] 2019-05-20 18:28
which version of Laravel are you using @vedmant ? You have to be specific in what version you add in composer. I don't think it works if you just add ^1.0

For example if you're using Laravel 5.7 you have to add 
`"tymon/jwt-auth": "1.0.0-rc.3",` and if you're using 5.8 then add `"tymon/jwt-auth": "1.0.0-rc.4.1",`

edit: scratch that, just tested, `"tymon/jwt-auth": "^1.0"`works fine and installs the latest release candidate.. at least it does on 5.8. If composer is telling you there's a problem with your deps, it's likely due with another package. Post your composer.json here and I can help

**Comment by vedmant** [comment] 2019-05-28 07:41
@vesper8 I use Laravel 5.7, I actually have following message: "The requested package tymon/jwt-auth ^1.0 is satisfiable by tymon/jwt-auth[1.0.0-alpha.2, 1.0.0-alpha.3, 1.0.0-alpha1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 1.0.0-rc.4, 1.0.0-rc.4.1, 1.0.x-dev] but these conflict with your requirements or minimum-stability."

Which means there is no stable 1.0 version? I don't what to change minimum stability to dev as it will affect other packages.

Ok, I found how to install it: `composer require tymon/jwt-auth:^1.0@dev`
