### ISSUE TITLE
JWTAuth requireToken($token) bug

### ISSUE THREAD

**Issue by MateuszKoguc** [tymondesigns/jwt-auth#791] opened 2016-07-14 08:11 UTC
I have a code

```
var_dump(JWTAuth::getToken());
JWTAuth::getPayload();
var_dump(JWTAuth::getToken());
JWTAuth::getPayload();
var_dump(JWTAuth::getToken());
```

which outputs:

```
object(Tymon\JWTAuth\Token)[305]
  private 'value' => string 'my.token.here' (length=296)

object(Tymon\JWTAuth\Token)[304]
  private 'value' => 
    object(Tymon\JWTAuth\Token)[305]
      private 'value' => string 'my.token.here' (length=296)

object(Tymon\JWTAuth\Token)[314]
  private 'value' => 
    object(Tymon\JWTAuth\Token)[304]
      private 'value' => 
        object(Tymon\JWTAuth\Token)[305]
          private 'value' => string 'my.token.here' (length=296)
```

every call it's adding next nested level. I use newest `0.5.9` version.

Temporary fix in `src/JWTAuth.php`:
before:

```
    protected function requireToken($token)
    {
        if (! $token = $token ?: $this->token) {
            throw new JWTException('A token is required', 400);
        }

        return $this->setToken($token);
    }
```

after:

```
    protected function requireToken($token)
    {
        if (! $token = $token ?: $this->token) {
            throw new JWTException('A token is required', 400);
        }

        if ($token instanceof Token) {
            return $this->setToken($token->get());
        }

        return $this->setToken($token);
    }
```

**Comment by tdhsmith** [comment] 2016-07-15 20:16
I think all of these issues were resolved in 1.0, but it looks like they weren't addressed in 0.5.

I believe @tymondesigns is on the record as not wanting to implement "automatic unwrapping" because it doesn't address the root cause of incorrect argument types (which I agree with). That said it does look like the logical flaw is here in `requireToken`. Maybe a better approach is just to separate the argument and null-argument cases:

```php
protected function requireToken($token)
{
    if ($token) {
        return $this->setToken($token);
    } else {
        if($this->token) {
            return $this;
        } else {
            throw new JWTException('A token is required', 400);
        }
    }
}
```

The question is, do we assume that all tokens coming from outside the library are strings? Otherwise you can't just plug `JWTAuth::getToken()` into `JWTAuth::setToken()` without some unwrapping...

**Closed** 2018-01-22 19:28 UTC
